### ISSUE TITLE
Errors connecting to postgres

### ISSUE THREAD

**Issue by willwill96** [snowplow-incubator/snowplow-postgres-loader#77]
**Version**: 0.3.3

**Expected behavior**: Can set up a postgres db for use in postgres-loader

**Actual behavior**: Having trouble setting up postgres

**Steps to reproduce**: 

I have a [repro located here](https://github.com/willwill96/snowplowio-demo)

 1. `git clone https://github.com/willwill96/snowplowio-demo.git`
 2. `docker-compose up` 

I have been trying to get set up with snowplow using localstack to get a better understanding of the moving pieces, but I am stuck on loading the enriched data into a postgres db. I'm using a pretty vanilla postgres db image.

With the minimal configuration, I see the following error:
```
snowplow-postgres-loader_1  | org.postgresql.util.PSQLException: ERROR: schema "atomic" does not exist
snowplow-postgres-loader_1  |   Position: 14
snowplow-postgres-loader_1  |   at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
```

Then I found this [SQL statement](https://github.com/snowplow/snowplow/blob/master/4-storage/redshift-storage/sql/atomic-def.sql), supposedly used only for Redshift apps. 

I added that SQL statement to the startup of my postgres db, but now I am getting the following error:
```
snowplow-postgres-loader_1  | org.postgresql.util.PSQLException: The connection attempt failed.
snowplow-postgres-loader_1  |   at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:331)
```
I'm not sure if this is the proper approach though, because [this doc](https://github.com/snowplow/snowplow/tree/master/4-storage) seems to suggest that the creation of DB & schema should be handled by the postgres loader.

Hoping someone may be able to provide some insights in what I might be doing wrong.

**Comment by voropaevp** [comment]
Postgres loader doesn't create the schema, but it would create `events` and other tables. Check docs over [here](https://docs.snowplow.io/docs/pipeline-components-and-applications/loaders-storage-targets/snowplow-postgres-loader/)
